name: Infinite Fate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09575
title: Infinite Fate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.44363991008140147
  lightness: 0.3125
  saturation: 0.7765595614910126
  rhythmicContrast: 0.75
purpose: []
